FROM grafana/grafana:7.0.0

COPY ./provisioning/datasources /etc/grafana/provisioning/datasources/
COPY ./provisioning/dashboards.yml /etc/grafana/provisioning/dashboards/
COPY ./provisioning/dashboards /etc/grafana/dashboards/
