global:
  scrape_interval:     15s
  evaluation_interval: 15s 

  external_labels:
      monitor: 'codart_alert'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

# alert
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
    scheme: http
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'local_traefik'
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: ['traefikmetrics:8082']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100